#define SET_BIT(REG,BIT)          (REG|=(1<<BIT))   
#define CLR_BIT(REG,BIT)          (REG&= ~(1<<BIT))
#define GET_BIT(REG,BIT)          ((REG>>BIT)&1)
#define TOGGLE_BIT(REG,BIT)       (REG^=(1<<BIT))
#define WRITE_BIT(REG,BIT,VALUE)  (REG = (VALUE<<BIT) | (REG&~(1<<BIT))  